### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by jianchengwang** [jianchengwang/playass#1]
- [ ] ioc 容器管理bean对象
- [ ] 自定义路由，支持resetful
- [ ] 参数自动转换，可以自动转换为map，lis，或者javabean等
- [ ] 结果渲染，可以返回json,html等
- [ ] 前置后置拦截器
- [ ] 文件上传跟下载
- [ ] 集成jwt,cookie,session等
- [ ] 配置脚本，自定义配置
- [ ] 插件机制，方便集成第三方的类库，
- [ ] 友好的日志输出
